### ISSUE TITLE
Lier les beans aux services

### ISSUE THREAD

**Issue by feliciencorbat** [HE-Arc-ODI/sp18-4igtp-proj-dev-tournoi#22]

**Comment by JoCharlet** [comment]
-  	addTeamTournament.xhtml 
- 	createTournament.xhtml 	
- 	deletePool.xhtml 
- 	detailsPlanification.xhtml 	
- 	detailsTournament.xhtml 	
- 	displayTournaments.xhtml
- 	editDatetime.xhtml 	
- 	editField.xhtml 	
- 	editPool.xhtml 	
- 	editReferee.xhtml 	
- 	editResult.xhtml 	
- 	editTournament.xhtml 	
- 	~~index.xhtml~~
- 	login.xhtml 	
- 	logout.xhtml 
- 	subscription.xhtml
