### ISSUE TITLE
Mettre en place l'intégration continue avec Jenkins

### ISSUE THREAD

**Issue by feliciencorbat** [HE-Arc-ODI/sp18-4igtp-proj-dev-tournoi#3]

**Comment by JoCharlet** [comment]
prod accessible ici --> http://chatbot.ig.he-arc.ch:43244/TournamentManagerProd/ 
dev accessible ici --> http://chatbot.ig.he-arc.ch:35697/TournamentManagerDEV/ 

Jenkins va builder la dev automatiquement dès qu'une branch d'intégration est mise à jour.
Pour la prod il va se baser sur la branch master
